OBJ Parser
ChatImproVR/iteration0 pull request #18
Opened 2023-03-17 03:52 UTC by toddgr

2023-03-17 06:49 UTC, Exiled1 commented
Is there any reason that theres two obj loader files?

2023-03-19 00:16 UTC, Masterchef365 requested changes
This is looking good! I'd like to suggest one change, which is to make the obj parser into a library instead of a plugin and a library like it is now. Then we can add an example plugin which uses the library. This way, other plugins such as the demo room can import and use the obj parser. The example plugin would use the library in the same way as other plugins would, so that it's clear how it's supposed to be imported and used.

2023-03-19 00:16 UTC, Masterchef365 commented on Cargo.toml
> +    "example_plugins/obj_parser"
This should now just be `"obj_parser"`, since it was moved to the crate root.

2023-03-19 00:16 UTC, Masterchef365 commented on obj_parser/Cargo.toml
> +cimvr_common = { path = "../../common" }
These two deps should be updated to reflect the new location of the crate! See `cargo check`.

2023-03-19 00:16 UTC, Masterchef365 commented on obj_parser/src/obj.rs
(Resolved)

2023-03-26 01:14 UTC, Exiled1 commented
Plz update the obj loader with main.

2023-04-03 21:40 UTC, closed without merging